# Generated by Django 4.2.11 on 2024-04-23 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wine", models.CharField(max_length=200)),
                ("shop", models.CharField(max_length=200)),
                ("day", models.DateField()),
                ("occasion", models.CharField(max_length=200)),
                ("rating", models.IntegerField()),
                (
                    "pic",
                    models.ImageField(blank=True, null=True, upload_to="diary_pics/"),
                ),
                ("memory", models.TextField(blank=True, null=True)),
                ("foodpairing", models.TextField(blank=True, null=True)),
                ("again", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rating"],
                "unique_together": {("user", "wine", "day")},
            },
        ),
    ]
