# Generated by Django 4.2.11 on 2024-04-25 01:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinoteka", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
