# Generated by Django 4.2.11 on 2024-04-25 03:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinoteka", "0003_alter_diary_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="pic",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="placeholder",
                max_length=255,
                null=True,
                verbose_name="img",
            ),
        ),
    ]
