# Generated by Django 4.2.11 on 2024-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(choices=[(0, "Draft"), (1, "Published")], default=0),
        ),
        migrations.AlterField(
            model_name="post", name="winery", field=models.CharField(max_length=100),
        ),
    ]
