# Generated by Django 4.2.11 on 2024-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_region_alter_post_status_alter_post_winery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "draft"), (1, "published")], default=0
            ),
        ),
    ]
